
### Obtain tokens via login (optional helper)
POST http://localhost:8080/v1/api/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "23467811"
}


###
POST http://localhost:8082/v1/api/universes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ0cmFkaW5nLWF1dGgiLCJzdWIiOiIwMjlmMjJjZS0yMWIyLTQ4MjItOGViMS0wMjQzNDZlM2ExZTUiLCJpYXQiOjE3Njg0NDA2NTUsImV4cCI6MTc2ODQ0OTY1NSwicm9sZSI6IlVTRVIifQ.7uAcdr_lkz9soJJJ1nTnlUw6TJFZrYjENFM-w79p8FA

{
  "name": "테스트 종목2",
  "description": "테스트2"
}

###cd866061-08f8-461a-9a3e-10d1258689e1,000880
#7778886a-9ae3-46ce-83a3-8526022f3a04,042660
#73a76f6f-7c69-4f66-8d82-8d33adaf9299,272210
#8ef166d0-cd5b-4ee5-9cfa-1354dd31e026,012450
#e27ff3fc-401d-4dfc-986e-4b0f27be4525,000660
POST http://localhost:8082/v1/api/universes/268984484750237696/instruments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ0cmFkaW5nLWF1dGgiLCJzdWIiOiIwMjlmMjJjZS0yMWIyLTQ4MjItOGViMS0wMjQzNDZlM2ExZTUiLCJpYXQiOjE3NjgzNzMwNjgsImV4cCI6MTc2ODM4MjA2OCwicm9sZSI6IlVTRVIifQ.WhlKPjodRxzUKusDgtDrF4fdJdDQG-kPwD1_OlerxK8

{
  "instrumentId": "e27ff3fc-401d-4dfc-986e-4b0f27be4525"
}

###
GET http://localhost:8082/v1/api/universes/268984484750237696/instruments
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ0cmFkaW5nLWF1dGgiLCJzdWIiOiIwMjlmMjJjZS0yMWIyLTQ4MjItOGViMS0wMjQzNDZlM2ExZTUiLCJpYXQiOjE3NjgzNzMwNjgsImV4cCI6MTc2ODM4MjA2OCwicm9sZSI6IlVTRVIifQ.WhlKPjodRxzUKusDgtDrF4fdJdDQG-kPwD1_OlerxK8


###
GET http://localhost:8082/v1/api/universes/internal/targets?intervalCd=1d&market=KR_STOCK&limit=1000
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ0cmFkaW5nLWF1dGgiLCJzdWIiOiIwMjlmMjJjZS0yMWIyLTQ4MjItOGViMS0wMjQzNDZlM2ExZTUiLCJpYXQiOjE3Njg0NTg3MzgsImV4cCI6MTc2ODQ2NzczOCwicm9sZSI6IlVTRVIifQ.9PPhXOMiEnLhb8MIdR3WDzf28RKlHDJ_huRfMj7-l88
Accept: application/json