
###
POST http://localhost:8083/v1/api/md/ingest/bars
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ0cmFkaW5nLWF1dGgiLCJzdWIiOiIwMjlmMjJjZS0yMWIyLTQ4MjItOGViMS0wMjQzNDZlM2ExZTUiLCJpYXQiOjE3NjgyNzg1OTMsImV4cCI6MTc2ODI4NzU5Mywicm9sZSI6IlVTRVIifQ.nluBgUnTRIhQzD-B_Lu7T5uJX_OrapbjZjty-53Zp-Y

{
  "instrumentId": "0006dadf-45da-475d-b8a3-c178c276633c",
  "intervalCd": "1d",
  "from": "2026-01-13",
  "to": "2026-01-14"
}